{{- $v := include "common.values" . | fromYaml -}}
{{- range $key, $secret := $v.secrets }}
{{- if and $secret (ne $secret.create false) (not (and $v.global.externalSecrets.enabled $secret.external)) }}
---
apiVersion: v1
kind: Secret
metadata:
  {{- include "common.metadata" (list $ (include "common.resourceName" (list $ $key))) | nindent 2 }}
type: {{ $secret.type | default "Opaque" }}
{{- with $secret.stringData }}
stringData:
  {{- include "common.dataEntries" (list $ .) | trim | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
